# See https://github.com/helm/chart-testing

# note: all the values files in ci/*-values.yaml will
#       be tested automatically. For each configuration,
#       all the tests in templates/tests/*.yaml
#       will be checked.

debug: true

################################################
# github
################################################
remote: origin

################################################
# chart
################################################
namespace: example
release-label: chart-template
charts:
  - ./
chart-dirs:
  - ./

################################################
# checks and validations
################################################
skip-existing: true
validate-chart-schema: true
validate-yaml: true
check-version-increment: true 
print-config: true
