# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files

  - repo: https://github.com/norwoodj/helm-docs
    rev: v1.14.2
    hooks:
      - id: helm-docs
        args:
          # Make the tool search for charts only under the `example-charts` directory
          - --chart-search-root=charts

          # The `./` makes it relative to the chart-search-root set above
          - --template-files=./_templates.gotmpl

          # Repeating the flag adds this to the list, now [./_templates.gotmpl, README.md.gotmpl]
          # A base filename makes it relative to each chart directory found
          - --template-files=README.md.gotmpl

repos:
-   repo: https://github.com/thlorenz/doctoc
    rev: v2.2.0
    hooks:
    -   id: doctoc

# -  id: doctoc
#    name: doctoc
#    language: node
#    entry: doctoc
#    types: [markdown]
#
# - repo: https://github.com/google/yamlfmt
#   rev: v0.14.0
#   hooks:
#     - id: yamlfmt
#
# - repo: https://github.com/gitleaks/gitleaks
#   rev: v8.23.1
#   hooks:
#     - id: gitleaks
# #
# #- id: check-yaml
# #  exclude: ^charts/*/templates/
#
# #repos:
# #  - repo: https://github.com/commitizen-tools/commitizen
# #    rev: master
# #    hooks:
# #      - id: commitizen
# #      - id: commitizen-branch
# #        stages: [push]
