apiVersion: v2
name: metallb
description: Installs MetalLB
type: application
maintainers:
  - name: kriipke
    email: kriipke@ziinc.dev
version: 0.1.4
appVersion: "0.14.9"
dependencies:
  - name: metallb
    version: 0.14.9
    repository: https://metallb.github.io/metallb
