gitOpsRepository:
  url: ""
  targetRevision: "HEAD"
  bootstrapPath: ""
  sshPrivateKeyBase64: ""

argo-cd:

  dex:
    enabled: true

  notifications:
    enabled: true

  applicationSet:
    enabled: true
    resources: {}
      # limits:
      #   cpu: 100m
      #   memory: 128Mi
      # requests:
      #   cpu: 100m
      #   memory: 128Mi
    extraArgs: []

  server:
    autoscaling:
      enabled: true
      minReplicas: 1
      maxReplicas: 5
    extraArgs:
      - --insecure
    resources: {}
    #  limits:
    #    cpu: 100m
    #    memory: 128Mi
    #  requests:
    #    cpu: 50m
    #    memory: 64Mi

  repoServer:
    autoscaling:
      enabled: true
      minReplicas: 1
      maxReplicas: 5
    resources: {}
    #  limits:
    #    cpu: 50m
    #    memory: 128Mi
    #  requests:
    #    cpu: 10m
    #    memory: 64Mi

argo-rollouts:
  extraObjects: []
