argo-cd:

  extraObjects:
    - apiVersion: argoproj.io/v1alpha1
      kind: Application
      metadata:
        name: appset-bootstrap
        namespace: argo-cd
      spec:
        project: default
        source:
          repoURL: https://github.com/kriipke/gitops
          targetRevision: HEAD
          path: bootstrap
        destination:
          server: https://kubernetes.default.svc
          namespace: argo-cd
        syncPolicy:
          automated:
            prune: true
            selfHeal: true  

  dex:
    enabled: true

  notifications:
    enabled: true

  applicationSet:
    enabled: true
    resources: {}
      # limits:
      #   cpu: 100m
      #   memory: 128Mi
      # requests:
      #   cpu: 100m
      #   memory: 128Mi
    extraArgs: []

  server:
    autoscaling:
      enabled: true
      minReplicas: 1
      maxReplicas: 5
    extraArgs:
      - --insecure
    resources: {}
    #  limits:
    #    cpu: 100m
    #    memory: 128Mi
    #  requests:
    #    cpu: 50m
    #    memory: 64Mi

  repoServer:
    autoscaling:
      enabled: true
      minReplicas: 1
      maxReplicas: 5
    resources: {}
    #  limits:
    #    cpu: 50m
    #    memory: 128Mi
    #  requests:
    #    cpu: 10m
    #    memory: 64Mi

argo-rollouts:
  extraObjects: []
