name: Generate Helm README.md

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v3
      with:
        fetch-depth: '2'
        
    - run: curl -sSL https://github.com/norwoodj/helm-docs/releases/download/v1.14.2/helm-docs_1.14.2_Linux_x86_64.tar.gz | tar -xzvf - && ls -l
    - run: |
       CHART_DIRS=`find ./charts -maxdepth 1 -type d` && echo $CHART_DIRS
       REPO_ROOT=`git rev-parse --show-toplevel`

       HELM_CHARTS="$(find  ${REPO_ROOT}/charts -maxdepth 1 -type d -exec  realpath --relative-to="$REPO_ROOT" {} \;)"
       HELM_CHARTS=$( echo "$HELM_CHARTS" | tail -n +2 )
       echo "HELM_CHARTS:" "$HELM_CHARTS"
       MODIFIED_FILES="$(git diff --name-only HEAD HEAD~1)"
       echo MODIFIED_FILES $MODIFIED_FILES 

       # CHECK IF EACH CHART HAS BEEN CHANGED

       declare -a MODIFIED_CHARTS
       
       for i in $HELM_CHARTS; do

         CHART_PATH=`realpath --relative-to="$REPO_ROOT" "$i"`
         CHART_NAME=`basename "$CHART_PATH"`
         printf '\nchart: %s, path: %s' "$CHART_NAME" `realpath "$CHART_PATH"`
         
         `echo $MODIFIED_FILES | grep -q "$i"` && { 
           echo HELM CHART CHANGED $i;
           MODIFIED_CHARTS+=("$CHART_NAME")
           echo MODIFIED_CHARTS_JUSTADDED "${MODIFIED_CHARTS[@]}"
         }
         
       done
       
       echo && echo MODIFIED_CHARTS: "${MODIFIED_CHARTS[@]}"
       if [[ ${#MODIFIED_CHARTS[@]} -eq 0 ]]; then
          echo "No modified charts found."
       else
          for element in "${MODIFIED_CHARTS[@]}"; do
            echo "$element"
          done
       fi


