name: mysql-operator

on:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: create kind cluster
        run: kind create cluster --kubeconfig kubeconfig --config kind-config.yml --wait 30s
      - name: helm repo add and update
        run: |
          helm version
          helm repo add nakamasato https://nakamasato.github.io/helm-charts
          helm repo update
      - name: helm install mysql-operator
        run: helm install mysql-operator nakamasato/mysql-operator
      - name: run mysql
        run: kubectl apply -k https://github.com/nakamasato/mysql-operator/config/mysql
