name: mysql-operator

on:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
#       - name: create kind cluster
#         run: kind create cluster --kubeconfig kubeconfig --config kind-config.yml --wait 30s
