name: Determine Modified Helm Charts

on:
  workflow_call:
    # Map the workflow outputs to job outputs
    outputs:
      modifiedCharts:
        description: "List of Helm Charts changed since the last commit"
        value: ${{ jobs.example_job.outputs.modifiedCharts }}
      modifiedFiles:
        description: "List of all files changed since the last commit"
        value: ${{ jobs.example_job.outputs.modifiedFiles }}

jobs:
  chart-diff:
    name: Generate output
    runs-on: ubuntu-latest
    # Map the job outputs to step outputs
    outputs:
      modifiedCharts: ${{ steps.gitdiff.outputs.charts }}
      modifiedFiles: ${{ steps.gitdiff.outputs.files }}
    steps:
      - name: Detect MODIFIED Helm charts
        id: gitdiff
        run: |
          REPO_ROOT=`git rev-parse --show-toplevel`
          printf "\nREPO_ROOT:\n%s" "$REPO_ROOT"
  
          MODIFIED_FILES="$(git diff --name-only HEAD HEAD~1)"
          printf "\nMODIFIED_FILES:\n%s" "$MODIFIED_FILES"

          HELM_CHARTS="$(find  ${REPO_ROOT}/charts -mindepth 1 -maxdepth 1 -type d -exec  realpath --relative-to="$REPO_ROOT" {} \;)"
          printf "\nHELM_CHARTS:\n%s" "$HELM_CHARTS"
  
          declare -a MODIFIED_CHARTS
          for i in $HELM_CHARTS; do
            REL_CHART_PATH="$i"       
            ABS_CHART_PATH="$(realpath "$i")"
            
            printf '\nchart: %s,\tpath: %s' `basename "$RELATIVE_CHART_PATH"` "$ABS_CHART_PATH"
  
            # -- CHECK IF EACH CHART HAS BEEN CHANGED         
            `echo $MODIFIED_FILES | grep -q "$REL_CHART_PATH"` && { 
              echo HELM CHART CHANGED "$REL_CHART_PATH";
              MODIFIED_CHARTS+=($ABS_CHART_PATH)
            }
          done
          
          echo "files=$(echo $MODIFIED_FILES | paste -d, -s - ) >> $GITHUB_OUTPUT
          echo "charts=$(IFS=',' && echo "$MODIFIED_CHARTS[*]") >> $GITHUB_OUTPUT
          
