apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: appset-bootstrap
  namespace: {{ .Release.Namespace }}
spec:
  project: default
  source:
    repoURL: {{ .Values.gitOpsRepository.url }}
    targetRevision: {{ .Values.gitOpsRepository.targetRevision }}
    path: {{ .Values.gitOpsRepository.bootstrapPath }}
  destination:
    server: https://kubernetes.default.svc
    namespace: {{ .Release.Namespace }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true  
