kind: Secret
apiVersion: v1
metadata:
  labels:
    argocd.argoproj.io/secret-type: repository
  name: repo-gitops
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  insecure: {{ "true" | b64enc }}
  name: {{ "repo-gitops" | b64enc }}
  project: {{ "default" | b64enc }}
  sshPrivateKey: {{ required "Must provide sshPrivateKeyBase64 under .Values.gitOpsRepository" .Values.gitOpsRepository.sshPrivateKeyBase64 }}
  type: {{ "git" | b64enc }}
  url: {{ .Values.gitOpsRepository.url | b64enc }}

