apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: ingress
  namespace: metallb-system
spec:
  addresses:
  - {{ .Values.ingress.ip }}/32
  autoAssign: false
  namespaceSelectors:
    - matchLabels:
        ipaddresspool: ingress
