apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: ingress
  namespace: metallb-system
spec:
  addresses:
  {{- range .Values.ipAddressPool }}
  {{- printf "- %s/32" . | nindent 4 }}
  {{- end }}
  autoAssign: true
